config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => 'dashboard#new'
  devise_for :users 
  #devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  resources :dashboard, only: [:new] 
  
  resources :images do
    collection do
      get 'get_image_detail'
      get 'check_image_name'
      get 'image_count'
      post 'import_images'
    end  
  end 

  resources :static_content, only: [:new] do
  	collection do 
  		get 'about_us'
      get 'contact_us_form'
      post 'contact_us_create'
  	end	
  end	

  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  # apis routes
  namespace :apis do
    resources :static_content, only: [:new] do
      collection do 
        post 'contact_us'
      end 
    end 
    resources :users, only: [:create] 
    resources :images, only:[:create, :show]
  end  

    # having created corresponding controller and action
    get '*path', to: 'dashboard#error_404', via: :all
    post '*path', to: 'dashboard#error_404', via: :all
    put '*path', to: 'dashboard#error_404', via: :all
    delete '*path', to: 'dashboard#error_404', via: :all

end

app/controllers/apis/static_content_controller.rb
class Apis::StaticContentController < ApplicationController
	before_filter :is_json?

	def contact_us
		if params[:contact_us].present?
		  return	render_message 500, "name is not found in request", "Failure" unless params[:contact_us][:name].present?
		  return	render_message 500, "email is not found in request", "Failure" unless params[:contact_us][:email].present?
		  return	render_message 500, "description is not found in request", "Failure" unless params[:contact_us][:description].present?
			name= params[:contact_us][:name]
			email= params[:contact_us][:email]
			desc= params[:contact_us][:description]
			UserMailer.contact_us_mail(name,email,desc).deliver rescue  (return render_message 500,"Some error found in sending mail!", "Failure")
			render_message 200, "Success","Thank you for contacting us!"
		else
			render_message 500, "Contact hash is missing in request", "Failure"
		end	
	end



end

app/controllers/static_content_controller.rb
class StaticContentController < ApplicationController
	before_action :authenticate_user!
	
	def about_us
		
	end

	def contact_us_form
		
	end

	def contact_us_create
		@name= params[:contact_us][:name]
		@email= params[:contact_us][:email]
		@desc= params[:contact_us][:description]
		StaticContentWorker.perform_async(@name,@email,@desc)
		#UserMailer.contact_us_mail(@name,@email,@desc).deliver
		flash[:notice]= "Thank you for contacting us!"
		redirect_to contact_us_form_static_content_index_path
	end
end

app/helpers/apis/static_content_helper.rb
module Apis::StaticContentHelper
end

app/helpers/static_content_helper.rb
module StaticContentHelper
end

app/views/static_content/about_us.html.haml
%div
  %center
    %h2
      About Maropost
    = image_tag "/assets/maro_image.png"
  .row
    .col-sm-8
      %p
        Maropost is the leading global provider of on-demand marketing, sales, commerce, and infrastructure solutions. We offer the world’s best marketing and sales cloud platforms combined with industry leading customer support and client success.
      %p
        From web, to mobile, to social, and across email, SMS, and digital, our Marketing Cloud offers the industry’s most advanced personalization and automation features – all to make your life easier and to increase your marketing ROI.
      %p
        Maropost was founded in 2011 by CEO and Chairman Ross Andrew Paquette. We are headquartered in Toronto, Canada, with offices in New York, USA, London, U.K., and Chandigarh, India.
      %p
        Maropost Sales Cloud is the all-in-one platform for your sales, customer service, and commerce departments. Our Sales Cloud was built from the ground up to offer combined insight and complete integration for a 360 business view. With our first-class customer support, we’ve built the last sales platform you’ll ever use. And the best part? You can choose and customize what features you want. Because the challenges your business is facing are unique, and you need a tailored solution for maximum success.
    .col-sm-4
      = image_tag "/assets/dummy_image.png"

app/views/static_content/contact_us_form.html.haml
.row
  .col.col-md-8
    = form_for :contact_us, url: contact_us_create_static_content_index_path, html:{id: "contact_us_form"} do |f|
      .form-group
        = f.label :name, "Name:"
        = f.text_field :name, class: "form-control", placeholder: "Enter Name"
      .form-group
        = f.label :email, "Email address:"
        = f.email_field :email, autofocus: true, class: "form-control", placeholder: "Enter email"
      .form-group
        = f.label :mobile_no, "Mobile No:"
        = f.text_field :mobile_no,  class: "form-control", placeholder: "Enter mobile no"
      .form-group
        = f.label :description, "Description:"
        = f.text_area :description,  class: "form-control", placeholder: "Enter Description",   :rows => 10, id: "text_area_width"
      .form-group{:align => "center"}
        %button.btn.btn-default{:type => "submit"} Submit
  .col-6.col-md-4
    %iframe{:allowfullscreen => "", :frameborder => "0", :height => "300", :src => "https://www.google.com/maps/embed/v1/place?key=AIzaSyDBvzq5WsidARhAZ0821MB1iAMTPnHiamI&q=155 University Ave Suite 1900, Toronto, ON M5H 3B7, Canada", :style => "border:0", :width => "500"}