config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => 'dashboard#new'
  devise_for :users 
  #devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  resources :dashboard, only: [:new] 
  
  resources :images do
    collection do
      get 'get_image_detail'
      get 'check_image_name'
      get 'image_count'
      post 'import_images'
    end  
  end 

  resources :static_content, only: [:new] do
  	collection do 
  		get 'about_us'
      get 'contact_us_form'
      post 'contact_us_create'
  	end	
  end	

  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  # apis routes
  namespace :apis do
    resources :static_content, only: [:new] do
      collection do 
        post 'contact_us'
      end 
    end 
    resources :users, only: [:create] 
    resources :images, only:[:create, :show]
  end  

    # having created corresponding controller and action
    get '*path', to: 'dashboard#error_404', via: :all
    post '*path', to: 'dashboard#error_404', via: :all
    put '*path', to: 'dashboard#error_404', via: :all
    delete '*path', to: 'dashboard#error_404', via: :all

end

app/controllers/apis/images_controller.rb
class Apis::ImagesController < ApplicationController
	before_filter :is_json?
	before_filter :find_user, only:[:create]
	
	def create
		return	render_message 500, "Name is not found in request", "Failure" unless params[:image][:name].present?
		return	render_message 500, "Image url is not found in request", "Failure" unless params[:image][:image_url].present?
		params[:image][:image_url] = Photo.image_data(params[:image][:image_url]) 
		photo= @user.photos.new(image_params)
		if photo.valid? && photo.save!
			render :json => {
	        :responseCode => 200,
	        :responseStatus=> "Success",
	        :responseMessage => "Image created Successfully!",
	        :photo=> photo.as_json(:only => [:id, :name]).merge(image_url: photo.image_url.url)
	      }
		else
			render_message 500,photo.errors.full_messages , "Failure"
		end		
	end

	def show
		photo= Photo.find_by_id(params[:id])
		if photo.present?
			render :json => {
	        :responseCode => 200,
	        :responseStatus=> "Success",
	        :responseMessage => "Image fetched Successfully!",
	        :photo=> photo.as_json(:only => [ :name]).merge(image_url: photo.image_url.url)
	      }
		else
			render_message 500,"Image doesn't exist with this id", "Failure"
		end	
	end

	private
	def image_params
		params.require(:image).permit(:name, :image_url)
	end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
		before_action :authenticate_user!

		def new
			
		end

		def index
			@photos= Photo.all.page(params[:page]).per(6)
		end

		def create
			@photo = Photo.new(photo_params)
		  if @photo.valid? && @photo.save!
		  	flash[:notice]= "Photo added successfully!"
		  	redirect_to images_path
			else
				flash[:error] = @photo.errors.full_messages
				redirect_to images_path
			end	
		end

		def destroy
			@photo= Photo.find_by(id: params[:id])
			@photo.destroy
			flash[:notice]= "Photo deleted successfully!"
		  redirect_to images_path
		end

		
		def edit
			@photo= Photo.find_by(id: params[:id])
		end

		def update
			 @photo= Photo.find_by(id: params[:id])
			 @photo.assign_attributes(photo_params)	
		   if @photo.valid? && @photo.save
 		      redirect_to images_path, notice: "Photo Updated Successfully!"
	    else
				  redirect_to images_path, notice: @photo.errors.full_messages.first
			end
		end

		def get_image_detail
			@photo= Photo.find_by(id: params[:id])
			render :json=> { photo_name: @photo.name }
		end

		def check_image_name
			@photo = Photo.find_by_name(params[:name])
			if @photo
				render :json=> { photo_present: true }
			else
				render :json=> { photo_present: false }
			end			
		end

		def import_images
			begin
     		@photo= Photo.import(params[:file])
     		if @photo[:key]== "failed"
					return redirect_to images_path, notice:  @photo[:message]
				elsif	 @photo[:key]== "name_error"
					return redirect_to images_path, notice:  @photo[:message]
				else
					return redirect_to images_path, notice:  @photo[:message]
				end	
			rescue
     			redirect_to images_path, notice: "Invalid Csv file format!"		
			end
		end

		def image_count
			sleep 1
			photo_count = Photo.count || 0
			render :json=> { photo_count: photo_count }
		end

		private
		def photo_params
			params.require(:photo).permit(:name, :image_url)
		end
end

app/helpers/apis/images_helper.rb
module Apis::ImagesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_import_images.html.haml
%h3 Import Images
= form_tag import_images_images_path, multipart: true ,:id => 'import_form' do
  .form-group
    = file_field_tag :file, id:"csv_upload"
    .actions
      = submit_tag "Import"

app/views/images/_photo_edit_modal.html.haml
.modal.fade{:id => "editModal_#{photo.id}", :role => "dialog"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Edit Photo
      .modal-body
        = form_for photo, :url => {:action => "update", :id => photo.id, :controller => "images"}, html:{:multipart => true, id: "photo_edit_form"} do |f|
          .form-group
            = f.label :name, "Name"
            = f.text_field :name, class: "form-control image_name", id: "edit_image_name"
          .form-group
            = f.label :select_file, "Choose file"
            = f.file_field :image_url
            = image_tag(f.object.image_url.present? ? f.object.image_url : "http://res.cloudinary.com/charu/image/upload/v1472115259/qwagaihkng3jtsjzwlcc.png" ,:width => 50, :height => 50)
          .modal-footer
            = f.submit "Submit", class: "btn btn-primary"
            %button.btn.btn-danger{"data-dismiss" => "modal", :type => "button"} Cancel

app/views/images/_photo_new_modal.html.haml
/ Modal
#myModal.modal.fade{:role => "dialog"}
  .modal-dialog
    / Modal content
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Add Photo
      .modal-body
        = form_for :photo, url: images_path, method: :post, html:{:multipart => true, id: "photo_new_form"} do |f|
          .form-group
            = f.label :name, "Name"
            = f.text_field :name, class: "form-control"
          .form-group
            = f.label :select_file, "Choose file"
            = f.file_field :image_url, accept: "jpg,png,jpeg,gif", id: "image_upload"
          .modal-footer
            = f.submit "Submit", class: "btn btn-primary photo_create"
            %button.btn.btn-danger{"data-dismiss" => "modal", :type => "button"} Cancel

app/views/images/index.html.haml
.row
  .col-6.col-md-4
    %h3 Add Images
    %br/
    %button.btn.btn-default.add_photo{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"} Add Photo
  .col-6.col-md-4
    = render partial: "import_images"
  .col-6.col-md-4
    %h4.image_counter{:style => "color:yellow"} Image Counter
    #count_value{:style => "width:79px;height:89px;border:1px solid black;position:absolute;top:43%;left:48%;padding:2px;"}
      %img{:height => "89", :src => "/assets/loader3.gif", :width => "79"}/
%br/
.row.image_index
  - @photos.each do |photo|
    - cache(photo, :expires_in => 5.minutes) do
      .col-sm-4
        %h3= photo.name
        = image_tag(photo.image_url, :size => "300x200")  if photo
        %br/
        .actions{:align => "center"}
          %button.btn.btn-primary.btn-sm.photo_edit{:id => "#{photo.id}", :type => "button"} Edit
          = link_to 'Destroy', image_path(photo.id),                                                |
            data: {:confirm => 'Are you sure?'}, :method => :delete, class: "btn btn-danger btn-sm" |
      = render partial: "photo_edit_modal", locals: {photo: photo}
  - end if @photos
.form-group.pagination_div
  = paginate @photos, options: { 'data-no-turbolink' => true}
= render partial: "photo_new_modal"
:javascript
  $(document).ready(function() {
    $("#footer").removeClass("navbar-fixed-bottom")
  });

app/views/images/new.html.erb
new page
  

app/views/images/new.html.haml
new page